import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';

// Status bar yüksekliğini hesapla
const STATUSBAR_HEIGHT = Platform.OS === 'ios' ? 44 : StatusBar.currentHeight || 0;

const FriendsPageStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5F6FA',
        paddingTop: 0,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: 16,
        paddingVertical: 16,
        paddingTop: STATUSBAR_HEIGHT + 16,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1A1A1A',
        letterSpacing: 0.3,
        flex: 1,
        textAlign: 'left',
    },
    headerTitleWithBack: {
        marginLeft: 8,
    },
    headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 'auto',
    },
    headerButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 12,
        backgroundColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 1,
    },
    backButton: {
        marginRight: 8,
        zIndex: 10,
    },
    badge: {
        position: 'absolute',
        top: -5,
        right: -5,
        backgroundColor: '#FF3B30',
        borderRadius: 10,
        width: 20,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeText: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: 'bold',
    },
    content: {
        flex: 1,
    },
    friendsListContainer: {
        padding: 16,
        paddingBottom: 100, // Alt kısımda ekstra boşluk
    },
    listContainer: {
        flexGrow: 1, // İçeriğin tam görünmesi için
    },
    friendCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 4,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 0,
    },
    friendMainInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    profileImage: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#F0F0F0',
        borderWidth: 0,
    },
    friendInfo: {
        marginLeft: 16,
        flex: 1,
    },
    friendName: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1A237E',
        marginBottom: 4,
        letterSpacing: 0.3,
    },
    activeShareContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 12,
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderColor: '#C8E6C9',
    },
    activeShareText: {
        fontSize: 12,
        color: '#2E7D32',
        marginLeft: 4,
        fontWeight: '600',
    },
    actionButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    actionButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    actionButtonGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    searchSection: {
        flex: 1,
        padding: 16,
        backgroundColor: '#FFF',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        borderRadius: 12,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#F0F0F0',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    searchInput: {
        flex: 1,
        paddingVertical: 12,
        marginLeft: 8,
        fontSize: 16,
        color: '#2C3E50',
    },
    searchResultCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    searchResultImage: {
        width: 48,
        height: 48,
        borderRadius: 24,
    },
    searchResultInfo: {
        flex: 1,
        marginLeft: 16,
    },
    searchResultName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 4,
    },
    searchResultEmail: {
        fontSize: 14,
        color: '#666',
    },
    searchActionButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        minWidth: 110,
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchActionButtonText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: '600',
    },
    loader: {
        marginTop: 16,
    },
    requestsContainer: {
        flex: 1,
        backgroundColor: '#FFF',
    },
    requestsContentContainer: {
        padding: 16,
    },
    requestsSection: {
        marginBottom: 24,
    },
    requestCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    requestImage: {
        width: 56,
        height: 56,
        borderRadius: 28,
    },
    requestInfo: {
        flex: 1,
        marginLeft: 16,
    },
    requestName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 8,
    },
    requestButtons: {
        flexDirection: 'row',
        gap: 8,
    },
    requestButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
    },
    emptyRequestsContainer: {
        alignItems: 'center',
        padding: 32,
        backgroundColor: '#FFF',
        borderRadius: 12,
    },
    emptyRequestsText: {
        fontSize: 16,
        color: '#666',
        marginTop: 12,
        textAlign: 'center',
    },
    sharingOptionsContainer: {
        padding: 16,
        backgroundColor: '#FFF',
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 12,
    },
    friendChips: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 16,
    },
    friendChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    selectedChip: {
        backgroundColor: '#E8F5E9',
        borderColor: '#4CAF50',
        borderWidth: 1,
    },
    chipImage: {
        width: 24,
        height: 24,
        borderRadius: 12,
        marginRight: 8,
    },
    chipText: {
        color: '#2C3E50',
        fontSize: 14,
    },
    sharingButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    sharingButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 12,
        borderRadius: 12,
        marginHorizontal: 4,
    },
    instantShareButton: {
        backgroundColor: '#4CAF50',
    },
    liveShareButton: {
        backgroundColor: '#2196F3',
    },
    sharingButtonText: {
        color: '#FFF',
        fontWeight: '600',
        marginLeft: 8,
    },
    activeSharesSection: {
        padding: 16,
        backgroundColor: '#FFF',
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    shareCard: {
        backgroundColor: '#FFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    shareHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    friendAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
    },
    shareInfo: {
        flex: 1,
        marginLeft: 12,
    },
    username: {
        fontSize: 14,
        color: '#7F8C8D',
    },
    shareDetails: {
        marginTop: 8,
    },
    shareTypeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    shareTypeText: {
        marginLeft: 4,
        fontSize: 14,
        fontWeight: '500',
    },
    locationInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    locationText: {
        marginLeft: 4,
        fontSize: 14,
        color: '#666',
    },
    timeInfo: {
        marginTop: 8,
    },
    timeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    timeText: {
        marginLeft: 8,
        fontSize: 12,
        color: '#666',
    },
    stopShareButton: {
        padding: 8,
    },
    sharesContainer: {
        flex: 1,
    },
    sharesContentContainer: {
        padding: 16,
        paddingBottom: 100, // Alt kısımda ekstra boşluk
    },
    sharesSection: {
        marginBottom: 24,
    },
    quickShareSection: {
        marginBottom: 24, // Alt kısımda ek boşluk
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 32,
    },
    emptyText: {
        fontSize: 16,
        color: '#666',
    },
    shareName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
    },
    shareType: {
        fontSize: 14,
        color: '#7F8C8D',
    },
    emptyState: {
        alignItems: 'center',
        padding: 24,
    },
    emptyStateText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
    },
    emptySharesContainer: {
        alignItems: 'center',
        padding: 32,
        backgroundColor: '#FFF',
        borderRadius: 12,
        marginHorizontal: 16,
        marginTop: 8,
    },
    emptySharesText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
        marginTop: 12,
    },
    emptySharesSubText: {
        fontSize: 14,
        color: '#666',
        marginTop: 4,
        textAlign: 'center',
    },
    quickShareCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 3,
    },
    quickShareIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    quickShareInfo: {
        flex: 1,
    },
    quickShareTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 4,
    },
    quickShareDescription: {
        fontSize: 13,
        color: '#666',
    },
    friendSelectContainer: {
        marginVertical: 16,
    },
    subsectionTitle: {
        fontSize: 16,
        fontWeight: '500',
        color: '#666',
        marginBottom: 12,
    },
    friendSelectItem: {
        alignItems: 'center',
        marginRight: 16,
        opacity: 0.7,
    },
    selectedFriendItem: {
        opacity: 1,
    },
    friendSelectImage: {
        width: 56,
        height: 56,
        borderRadius: 28,
        marginBottom: 8,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    friendSelectName: {
        fontSize: 14,
        color: '#2C3E50',
        textAlign: 'center',
    },
    shareOptionsContainer: {
        marginTop: 16,
    },
    shareOption: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
    },
    shareOptionInfo: {
        marginLeft: 16,
    },
    shareOptionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
    },
    shareOptionDescription: {
        fontSize: 14,
        color: '#666',
        marginTop: 4,
    },
    shareTypeSection: {
        marginBottom: 16,
    },
    shareTypeTitle: {
        fontSize: 16,
        fontWeight: '500',
        color: '#666',
        marginBottom: 12,
        marginTop: 16,
    },
    viewLocationButton: {
        position: 'absolute',
        right: 16,
        top: 16,
        borderRadius: 20,
        overflow: 'hidden',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    viewButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    viewButtonText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 4,
    },
    noSharesText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginTop: 12,
    },
    addFriendsSection: {
        marginTop: 24,
    },
    addOptionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    addOptionIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#F5F6FA',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    addOptionInfo: {
        flex: 1,
    },
    addOptionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 4,
    },
    addOptionDescription: {
        fontSize: 14,
        color: '#666',
    },
    tipText: {
        fontSize: 13,
        color: '#666',
        fontStyle: 'italic',
        textAlign: 'center',
        marginTop: 8,
        marginBottom: 16,
    },
    cancelButton: {
        backgroundColor: '#FFF',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#FF3B30',
    },
    cancelButtonText: {
        color: '#FF3B30',
        fontSize: 14,
        fontWeight: '600',
    },
    requestUsername: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
    },
    welcomeText: {
        fontSize: 24,
        fontWeight: '600',
        color: '#666666', // Daha soluk bir gri renk
        marginBottom: 20,
        textAlign: 'center',
    },
    tabContent: {
        flex: 1,
    },
    friendsList: {
        padding: 16,
    },
    addButton: {
        backgroundColor: '#2196F3',
    },
    pendingButton: {
        backgroundColor: '#FFA000',
    },
    friendButton: {
        backgroundColor: '#4CAF50',
    },
    acceptButton: {
        backgroundColor: '#4CAF50',
    },
    modernViewButton: {
        position: 'absolute',
        right: 16,
        top: 16,
        borderRadius: 20,
        overflow: 'hidden',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    viewButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    viewButtonText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 4,
    },
    // Yeni paylaşım kartı stilleri
    shareCardNew: {
        borderRadius: 16,
        marginBottom: 16,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    shareCardGradient: {
        padding: 16,
        borderRadius: 16,
    },
    shareHeaderNew: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    shareUserInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    friendAvatarNew: {
        width: 50,
        height: 50,
        borderRadius: 25,
        borderWidth: 2,
        borderColor: '#FFF',
    },
    shareInfoNew: {
        marginLeft: 12,
        flex: 1,
    },
    friendNameNew: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
    },
    usernameNew: {
        fontSize: 13,
        color: '#666',
        marginTop: 2,
    },
    shareTypeContainerNew: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.7)',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 12,
    },
    shareTypeTextNew: {
        marginLeft: 4,
        fontSize: 12,
        fontWeight: '600',
    },
    shareDetailsNew: {
        backgroundColor: 'rgba(255,255,255,0.7)',
        borderRadius: 12,
        padding: 12,
        marginTop: 8,
    },
    locationInfoNew: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    locationIconContainer: {
        width: 30,
        alignItems: 'center',
    },
    locationTextNew: {
        fontSize: 14,
        color: '#333',
        flex: 1,
    },
    timeInfoNew: {
        marginTop: 8,
        borderTopWidth: 1,
        borderTopColor: 'rgba(0,0,0,0.05)',
        paddingTop: 8,
    },
    timeRowNew: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    timeIconContainer: {
        width: 30,
        alignItems: 'center',
    },
    timeTextNew: {
        fontSize: 12,
        color: '#666',
    },
    stopShareButtonNew: {
        marginTop: 12,
        borderRadius: 12,
        overflow: 'hidden',
    },
    stopButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
    },
    stopButtonText: {
        color: '#FFF',
        fontWeight: '600',
        fontSize: 14,
        marginLeft: 6,
    },
});

export default FriendsPageStyles;